version: "3"
services:
  prod:
    image: "dbspy/mm-prod:latest"
    container_name: "production"
    ports: ["3000:3000"]
    volumes: ["./:/usr/src/app", "node_modules:/usr/src/app/node_modules"]
    command: npm run docker-prod
    
volumes:
  node_modules:
  